---
# tasks file for base
- name: System is up to date
  become: yes
  apt:
    update_cache: yes
    upgrade: yes
    autoremove: yes
- name: SSH server is configured
  become: yes
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
- name: SSH server trusts CA
  become: yes
  copy:
    content: "{{ lookup('hashivault', '/ssh/config/ca', 'public_key') }}"
    dest: /etc/ssh/trusted
- name: Sudo password is disabled
  become: yes
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
- name: Common user is configured
  become: yes
  user:
    name: josh
    groups: josh, sudo
    password: "{{ lookup('hashivault', 'user/josh', 'password') | password_hash('sha512') }}"
- name: Common tools are installed
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - unzip
- name: Vault is installed
  stat:
    path: /usr/local/bin/vault
  register: vault
- name: Download Vault
  get_url:
    url: https://releases.hashicorp.com/vault/1.4.1/vault_1.4.1_linux_amd64.zip
    dest: /tmp/vault.zip
  when: not vault.stat.exists
- name: Install Vault
  become: yes
  unarchive:
    src: /tmp/vault.zip
    dest: /usr/local/bin
    remote_src: yes
  when: not vault.stat.exists