## Values for the external vSphere Cloud Provider
external_vsphere_vcenter_ip: "vcenter.gilman.io"
external_vsphere_vcenter_port: "443"
external_vsphere_insecure: "true"
external_vsphere_user: "{{ lookup('hashivault', 'vsphere/api', 'username') }}"
external_vsphere_password: "{{ lookup('hashivault', 'vsphere/api', 'password') }}"
external_vsphere_datacenter: "Gilman"
external_vsphere_kubernetes_cluster_id: "gilman"

## Tags for the external vSphere Cloud Provider images
# external_vsphere_cloud_controller_image_tag: "latest"
# vsphere_syncer_image_tag: "v1.0.2"
# vsphere_csi_attacher_image_tag: "v1.1.1"
# vsphere_csi_controller: "v1.0.2"
# vsphere_csi_liveness_probe_image_tag: "v1.1.0"
# vsphere_csi_provisioner_image_tag: "v1.2.2"

## To use vSphere CSI plugin to provision volumes set this value to true
vsphere_csi_enabled: false
vsphere_csi_controller_replicas: 2
