---
- hosts: kube
  become: yes
  roles:
    - common
  tasks:
    - name: Disable SWAP since kubernetes can't work with swap enabled
      shell: swapoff -a
    - name: Disable SWAP in fstab since kubernetes can't work with swap enabled
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'
      register: fstab
    - name: NFS tools are installed
      package:
        name: nfs-common
        state: present
    - name: iSCSI installed
      apt:
        name: open-iscsi
        state: present
    - name: iSCSI enabled
      service:
        name: iscsid
        enabled: yes