---
- hosts: kubeworker*
  vars:
    #force_ssh_host: yes # Forcibly generate SSH host keys
    docker_users:
      - josh
    kubernetes_role: node
  roles:
    - ssh_server
    - common
    - { role: geerlingguy.docker, become: yes }
    - { role: geerlingguy.kubernetes, become: yes }