---
- hosts: Kubernetes
  roles:
    - common
    - ssh_server
  tasks:
    - name: Disable SWAP since kubernetes can't work with swap enabled
      become: yes
      shell: swapoff -a
    - name: Disable SWAP in fstab since kubernetes can't work with swap enabled
      become: yes
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'
      register: fstab
    - name: Reboot machines to finalize disabling swap
      become: yes
      reboot:
      when: fstab.changed

- hosts: Kubernetes_master
  vars:
    docker_users:
      - josh
    kubernetes_role: master
    kubernetes_enable_web_ui: true
    kubernetes_web_ui_manifest_file: https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml
  roles:
    - { role: geerlingguy.docker, become: yes }
    - { role: geerlingguy.kubernetes, become: yes }

- hosts: Kubernetes_worker
  vars:
    docker_users:
      - josh
    kubernetes_role: node
    kubernetes_kubelet_extra_args: "--node-ip={{ ansible_host }}"
  roles:
    - { role: geerlingguy.docker, become: yes }
    - { role: geerlingguy.kubernetes, become: yes }

- hosts: Kubernetes_master
  tasks:
    - name: Kube user directory exists
      file:
        path: "{{ ansible_env.HOME }}/.kube"
        state: directory
    - name: Kube admin config exists
        become: yes
        copy:
          src: /etc/kubernetes/admin.conf
          dest: "{{ ansible_env.HOME }}/.kube/config"
          owner: josh
          group: josh
          remote_src: yes