---
- hosts: kube
  roles:
    - common
  tasks:
    - name: Disable SWAP since kubernetes can't work with swap enabled
      become: yes
      shell: swapoff -a
    - name: Disable SWAP in fstab since kubernetes can't work with swap enabled
      become: yes
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'
      register: fstab
    - name: NFS tools are installed
      become: yes
      package:
        name: nfs-common
        state: present
    - name: Network configured
      become: yes
      copy:
        src: kube-network.yml
        dest: /etc/netplan/01-netcfg.yaml