---
- hosts: vagrant
  become: yes
  tasks:
    - name: System is up to date
      apt:
        update_cache: yes
        upgrade: yes
        autoremove: yes
    - name: Sudo password is disabled
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
    - name: Disable SWAP since kubernetes can't work with swap enabled
      shell: swapoff -a
    - name: Disable SWAP in fstab since kubernetes can't work with swap enabled
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'
      register: fstab
    - name: NFS tools are installed
      package:
        name: nfs-common
        state: present
    - name: iSCSI is installed
      package:
        name: open-iscsi
        state: present
    - name: iSCSI is enabled
      systemd:
        name: iscsid
        state: started
        enabled: yes